#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v26
# autospec commit: 99a7985
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : baloo
Version  : 6.14.0
Release  : 94
URL      : https://download.kde.org/stable/frameworks/6.14/baloo-6.14.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.14/baloo-6.14.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.14/baloo-6.14.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : A framework for searching and managing metadata
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 bzip2-1.0.6
Requires: baloo-bin = %{version}-%{release}
Requires: baloo-data = %{version}-%{release}
Requires: baloo-lib = %{version}-%{release}
Requires: baloo-license = %{version}-%{release}
Requires: baloo-locales = %{version}-%{release}
Requires: baloo-services = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig
BuildRequires : kconfig-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kidletime-dev
BuildRequires : kio-dev
BuildRequires : lmdb-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Baloo
## Introduction
Baloo is the file indexing and file search framework for KDE Plasma. It focuses
on speed and a very small memory footprint. It maintains an index of your files
and optionally their contents which [you can search](./docs/user/searching.md).

%package bin
Summary: bin components for the baloo package.
Group: Binaries
Requires: baloo-data = %{version}-%{release}
Requires: baloo-license = %{version}-%{release}
Requires: baloo-services = %{version}-%{release}

%description bin
bin components for the baloo package.


%package data
Summary: data components for the baloo package.
Group: Data

%description data
data components for the baloo package.


%package dev
Summary: dev components for the baloo package.
Group: Development
Requires: baloo-lib = %{version}-%{release}
Requires: baloo-bin = %{version}-%{release}
Requires: baloo-data = %{version}-%{release}
Provides: baloo-devel = %{version}-%{release}
Requires: baloo = %{version}-%{release}

%description dev
dev components for the baloo package.


%package lib
Summary: lib components for the baloo package.
Group: Libraries
Requires: baloo-data = %{version}-%{release}
Requires: baloo-license = %{version}-%{release}

%description lib
lib components for the baloo package.


%package license
Summary: license components for the baloo package.
Group: Default

%description license
license components for the baloo package.


%package locales
Summary: locales components for the baloo package.
Group: Default

%description locales
locales components for the baloo package.


%package services
Summary: services components for the baloo package.
Group: Systemd services
Requires: systemd

%description services
services components for the baloo package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n baloo-6.14.0
cd %{_builddir}/baloo-6.14.0
pushd ..
cp -a baloo-6.14.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747191586
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1747191586
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/baloo
cp %{_builddir}/baloo-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/baloo/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/baloo-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/baloo/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/baloo-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/baloo/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/baloo-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/baloo/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/baloo-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/baloo/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/baloo/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/baloo-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/baloo/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/baloo-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/baloo/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/baloo/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/baloo/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/baloo/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/baloo/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/baloo-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/baloo/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/baloo-%{version}/LICENSES/bzip2-1.0.6.txt %{buildroot}/usr/share/package-licenses/baloo/c86f08afa3409f52c8811ac27764e50469ef0bb0 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang baloo_file6
%find_lang baloo_file_extractor6
%find_lang balooctl6
%find_lang baloodb6
%find_lang balooengine6
%find_lang baloosearch6
%find_lang balooshow6
%find_lang kio6_baloosearch
%find_lang kio6_tags
%find_lang kio6_timeline
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/kf6/baloo_file
/V3/usr/lib64/libexec/kf6/baloo_file_extractor
/usr/lib64/libexec/kf6/baloo_file
/usr/lib64/libexec/kf6/baloo_file_extractor

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/balooctl6
/V3/usr/bin/baloosearch6
/V3/usr/bin/balooshow6
/usr/bin/balooctl6
/usr/bin/baloosearch6
/usr/bin/balooshow6

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.kde.BalooWatcherApplication.xml
/usr/share/dbus-1/interfaces/org.kde.baloo.file.indexer.xml
/usr/share/dbus-1/interfaces/org.kde.baloo.fileindexer.xml
/usr/share/dbus-1/interfaces/org.kde.baloo.main.xml
/usr/share/dbus-1/interfaces/org.kde.baloo.scheduler.xml
/usr/share/qlogging-categories6/baloo.categories
/usr/share/qlogging-categories6/baloo.renamecategories
/usr/share/xdg/autostart/baloo_file.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/Baloo/Baloo/File
/usr/include/KF6/Baloo/Baloo/FileMonitor
/usr/include/KF6/Baloo/Baloo/IndexerConfig
/usr/include/KF6/Baloo/Baloo/Query
/usr/include/KF6/Baloo/Baloo/QueryRunnable
/usr/include/KF6/Baloo/Baloo/ResultIterator
/usr/include/KF6/Baloo/Baloo/TagListJob
/usr/include/KF6/Baloo/baloo/baloosettings.h
/usr/include/KF6/Baloo/baloo/core_export.h
/usr/include/KF6/Baloo/baloo/file.h
/usr/include/KF6/Baloo/baloo/filemonitor.h
/usr/include/KF6/Baloo/baloo/indexerconfig.h
/usr/include/KF6/Baloo/baloo/query.h
/usr/include/KF6/Baloo/baloo/queryrunnable.h
/usr/include/KF6/Baloo/baloo/resultiterator.h
/usr/include/KF6/Baloo/baloo/taglistjob.h
/usr/include/KF6/Baloo/baloo_version.h
/usr/lib64/cmake/KF6Baloo/KF6BalooConfig.cmake
/usr/lib64/cmake/KF6Baloo/KF6BalooConfigVersion.cmake
/usr/lib64/cmake/KF6Baloo/KF6BalooTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6Baloo/KF6BalooTargets.cmake
/usr/lib64/libKF6Baloo.so
/usr/lib64/pkgconfig/KF6Baloo.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6Baloo.so.6.14.0
/V3/usr/lib64/libKF6BalooEngine.so.6.14.0
/V3/usr/lib64/qt6/plugins/kf6/kded/baloosearchmodule.so
/V3/usr/lib64/qt6/plugins/kf6/kio/baloosearch.so
/V3/usr/lib64/qt6/plugins/kf6/kio/tags.so
/V3/usr/lib64/qt6/plugins/kf6/kio/timeline.so
/V3/usr/lib64/qt6/qml/org/kde/baloo/experimental/libbaloomonitorplugin.so
/V3/usr/lib64/qt6/qml/org/kde/baloo/libbalooplugin.so
/usr/lib64/libKF6Baloo.so.6
/usr/lib64/libKF6Baloo.so.6.14.0
/usr/lib64/libKF6BalooEngine.so.6
/usr/lib64/libKF6BalooEngine.so.6.14.0
/usr/lib64/qt6/plugins/kf6/kded/baloosearchmodule.so
/usr/lib64/qt6/plugins/kf6/kio/baloosearch.so
/usr/lib64/qt6/plugins/kf6/kio/tags.so
/usr/lib64/qt6/plugins/kf6/kio/timeline.so
/usr/lib64/qt6/qml/org/kde/baloo/balooplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/baloo/experimental/baloomonitorplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/baloo/experimental/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/baloo/experimental/libbaloomonitorplugin.so
/usr/lib64/qt6/qml/org/kde/baloo/experimental/qmldir
/usr/lib64/qt6/qml/org/kde/baloo/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/baloo/libbalooplugin.so
/usr/lib64/qt6/qml/org/kde/baloo/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/baloo/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/baloo/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/baloo/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/baloo/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/baloo/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/baloo/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/baloo/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/baloo/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/baloo/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/baloo/c86f08afa3409f52c8811ac27764e50469ef0bb0
/usr/share/package-licenses/baloo/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/baloo/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/kde-baloo.service

%files locales -f baloo_file6.lang -f baloo_file_extractor6.lang -f balooctl6.lang -f baloodb6.lang -f balooengine6.lang -f baloosearch6.lang -f balooshow6.lang -f kio6_baloosearch.lang -f kio6_tags.lang -f kio6_timeline.lang
%defattr(-,root,root,-)

